fn main() {
    // The native file/folder dialogs import TaskDialogIndirect from Common Controls v6, which
    // only resolves in a process with a v6 manifest (the app has one via Tauri). Delay-loading
    // comctl32 resolves it on first use instead of at start-up, so unit-test binaries (no
    // manifest) can still start; the app behaves exactly the same.
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows")
        && std::env::var("CARGO_CFG_TARGET_ENV").as_deref() == Ok("msvc")
    {
        println!("cargo:rustc-link-arg=/DELAYLOAD:comctl32.dll");
        println!("cargo:rustc-link-arg=delayimp.lib");
    }
    // Re-embed the exe icon whenever the icon files change, so the taskbar/Task Manager
    // icon matches the window icon instead of a stale one from an earlier build.
    println!("cargo:rerun-if-changed=icons");
    println!("cargo:rerun-if-changed=tauri.conf.json");
    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=capabilities");

    // Least privilege: every app command gets its own permission (allow-<command>), and a
    // window may only call the commands its capability lists. The list is read from the
    // `generate_handler![...]` in lib.rs so it can't drift; the main window's capability is
    // generated with all of them, the Properties windows get a hand-picked few
    // (capabilities/properties.json).
    let lib = std::fs::read_to_string("src/lib.rs").expect("read src/lib.rs");
    let start = lib.find("generate_handler![").expect("generate_handler! in lib.rs") + "generate_handler![".len();
    let end = start + lib[start..].find(']').expect("end of generate_handler!");
    let commands: Vec<&'static str> = lib[start..end]
        .split(',')
        .map(|c| c.trim())
        .filter(|c| !c.is_empty())
        .map(|c| &*Box::leak(c.to_string().into_boxed_str()))
        .collect();
    let perms: Vec<String> = commands.iter().map(|c| format!("\"allow-{}\"", c.replace('_', "-"))).collect();
    let main_cap = format!(
        "{{\n  \"$schema\": \"../gen/schemas/desktop-schema.json\",\n  \"identifier\": \"main\",\n  \"description\": \"Main window. GENERATED by build.rs from generate_handler! in src/lib.rs - do not edit.\",\n  \"windows\": [\"main\"],\n  \"permissions\": [\n    \"core:default\",\n    \"core:window:allow-start-dragging\",\n    \"opener:default\",\n    {}\n  ]\n}}\n",
        perms.join(",\n    ")
    );
    let path = std::path::Path::new("capabilities/main.json");
    if std::fs::read_to_string(path).ok().as_deref() != Some(main_cap.as_str()) {
        std::fs::write(path, main_cap).expect("write capabilities/main.json");
    }
    // Anti-tamper: pin the SHA-256 of every bundled FFmpeg executable/library. The app refuses
    // to launch FFmpeg if any of them was replaced or modified after the build.
    println!("cargo:rerun-if-changed=ffmpeg");
    let mut pins = String::from("pub const FFMPEG_PINS: &[(&str, &str)] = &[\n");
    if let Ok(rd) = std::fs::read_dir("ffmpeg") {
        let mut files: Vec<_> = rd.filter_map(|e| e.ok()).map(|e| e.path()).filter(|p| matches!(p.extension().and_then(|e| e.to_str()).map(|e| e.to_ascii_lowercase()).as_deref(), Some("exe" | "dll" | "so" | "dylib") | None) && p.is_file()).collect();
        files.sort();
        for f in files {
            use sha2::Digest;
            let bytes = std::fs::read(&f).expect("read ffmpeg file");
            let hex: String = sha2::Sha256::digest(&bytes).iter().map(|b| format!("{b:02x}")).collect();
            pins.push_str(&format!("    ({:?}, {:?}),\n", f.file_name().unwrap().to_string_lossy(), hex));
        }
    }
    pins.push_str("];\n");
    std::fs::write(std::path::Path::new(&std::env::var("OUT_DIR").unwrap()).join("ffmpeg_pins.rs"), pins).expect("write pins");

    let commands: &'static [&'static str] = Box::leak(commands.into_boxed_slice());
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(commands)))
        .expect("tauri build");
}
