// Extracts the Fluent UI System Icons PiFiles uses into src/fluent-icons.js.
// Source: @fluentui/svg-icons (MIT, Microsoft) — dev dependency only; the app ships just this subset.
// Run: node scripts/build-icons.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dir = join(root, "node_modules/@fluentui/svg-icons/icons");

// PiFiles name -> Fluent icon file stem (20px regular outlines, tinted with currentColor).
const REGULAR = {
  back: "arrow_left", forward: "arrow_right", up: "arrow_up", refresh: "arrow_clockwise", reload: "arrow_sync",
  chevronRight: "chevron_right", chevronDown: "chevron_down", search: "search", add: "add", addCircle: "add_circle",
  cut: "cut", copy: "copy", paste: "clipboard_paste", rename: "rename", share: "share", delete: "delete",
  properties: "wrench", filter: "filter", sort: "arrow_sort", group: "group_list", list: "text_bullet_list_ltr",
  details: "apps_list", grid: "grid", pane: "panel_right", sidebar: "panel_left", settings: "settings",
  close: "dismiss", more: "more_horizontal", copyPath: "link", edit: "edit", selectAll: "select_all_on",
  newFolder: "folder_add", newFile: "document_add", recent: "history", tag: "tag", split: "split_vertical",
  person: "person", info: "info", palette: "color", layoutIco: "layout_row_two", folderLine: "folder",
  sidebarNav: "navigation", advanced: "options", keyboard: "keyboard", check: "checkmark",
  warning: "warning", question: "question_circle", eye: "eye", eyeOff: "eye_off",
  // media player / viewers
  play: "play", pause: "pause", volume: "speaker_2", mute: "speaker_mute", cc: "closed_caption",
  ccOff: "closed_caption_off", fullscreen: "full_screen_maximize", fullscreenExit: "full_screen_minimize",
  back10: "skip_back_10", fwd10: "skip_forward_10", music: "music_note_2", zip: "folder_zip", archive: "archive",
  table: "table", extract: "arrow_download", open: "open", lock: "lock_closed", speed: "top_speed",
  upLevel: "arrow_enter_up", sheet: "document_table", mouse: "cursor_click",
  // file operations, sharing, restore, editors, network, packs
  operations: "arrow_swap", copyTo: "copy_arrow_right", moveTo: "arrow_move", terminal: "window_console",
  restore: "arrow_counterclockwise", history: "history", shareNet: "folder_link", server: "server",
  computer: "desktop", phone: "phone", camera: "camera", videoClip: "video_clip", images: "image_multiple",
  tags: "tag_multiple", save: "save", undo: "arrow_undo", openFolder: "folder_open", exportIco: "arrow_export",
  importIco: "arrow_import", brush: "paint_brush", iconsIco: "icons", pauseCircle: "pause_circle",
  playCircle: "play_circle", cancel: "dismiss_circle", done: "checkmark_circle", error: "error_circle",
  docEdit: "document_edit", usb: "usb_stick", cloud: "cloud", openWith: "open_folder", apps: "apps_add_in",
  storage: "storage", hardDrive: "hard_drive", globe: "globe_desktop",
};
// Colourful 20px icons for places.
const COLOR = {
  home: "home", pin: "pin", pictures: "image", videos: "video", music: "headphones", documents: "document_text",
  network: "globe", people: "people", recent: "history", settings: "settings", devices: "phone_laptop",
  media: "image", code: "code", table: "table", book: "book", star: "star", warning: "warning", question: "question_circle",
};

function load(stem, kind) {
  const file = join(dir, `${stem}_20_${kind}.svg`);
  let svg = readFileSync(file, "utf8").trim();
  svg = svg.replace(/ width="\d+"/, "").replace(/ height="\d+"/, "");
  if (kind === "regular") svg = svg.replace("<svg ", '<svg fill="currentColor" ');
  return svg.replace("<svg ", '<svg aria-hidden="true" focusable="false" ');
}

const out = { regular: {}, color: {} };
for (const [name, stem] of Object.entries(REGULAR)) out.regular[name] = load(stem, "regular");
for (const [name, stem] of Object.entries(COLOR)) out.color[name] = load(stem, "color");

const js = `// Generated by scripts/build-icons.mjs from @fluentui/svg-icons (MIT, Microsoft). Do not edit.
window.PiFluentIcons = ${JSON.stringify(out, null, 0)};
`;
writeFileSync(join(root, "src/fluent-icons.js"), js);
console.log(`wrote src/fluent-icons.js: ${Object.keys(out.regular).length} regular + ${Object.keys(out.color).length} colour icons, ${(js.length / 1024).toFixed(1)} KB`);
